name: sesame_cloud_backup_supabase
description: Supabase provider for sesame_cloud_backup
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sesame_cloud_backup:
    path: ../sesame_cloud_backup
  supabase_flutter: ^2.0.0
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # This package is a Flutter plugin
