import 'package:flutter/widgets.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';

/// 分类/选择器图标库（DB 持久化反查注册表）。
///
/// 设计意图：把"语义 → 图标"的映射决策收敛到唯一文件，解决图标常量
/// 散落全仓、改一处要满仓找的痛点。本文件专注分类/选择器图标：
///
/// 分类/选择器图标（[lucideIconLibrary] Map）：DB 以字符串名持久化
/// 用户选择（`Category.icon`），调用点只拿到字符串，必须由 Map 反查
/// [IconData]——字符串键因此不能直接作为静态 token 引用。
///
/// 维护约定：新增分类/选择器图标时同步在 Map 中加一条映射。键名与
/// LucideIcons 成员名保持一致。

/// 兜底图标：分类名未命中 [lucideIconLibrary] 时统一回退，杜绝渲染问号。
const lucideFallback = LucideIcons.helpCircle;

/// 分类/选择器图标库：DB 以字符串名持久化，运行时按名反查。
///
/// 闭集，随 seed 分类与选择器网格的增删而维护。所有值均为 Lucide 单色
/// 描边字形，可随主题 color 着色。
final Map<String, IconData> lucideIconLibrary = {
  // 基础
  'category': LucideIcons.shapes,
  'helpCircle': LucideIcons.helpCircle,
  'tag': LucideIcons.tag,
  'bookmark': LucideIcons.bookmark,
  'star': LucideIcons.star,
  'heart': LucideIcons.heart,
  'circle': LucideIcons.circle,

  // 餐饮美食
  'utensils': LucideIcons.utensils,
  'utensilsCrossed': LucideIcons.utensilsCrossed,
  'coffee': LucideIcons.coffee,
  'pizza': LucideIcons.pizza,
  'sandwich': LucideIcons.sandwich,
  'beer': LucideIcons.beer,
  'wine': LucideIcons.wine,
  'martini': LucideIcons.martini,
  'cake': LucideIcons.cake,
  'cakeSlice': LucideIcons.cakeSlice,
  'iceCream': LucideIcons.iceCream,
  'croissant': LucideIcons.croissant,
  'cookie': LucideIcons.cookie,
  'candy': LucideIcons.candy,
  // 棒棒糖：零食一级分类默认图标（seed_service getDefaultIcon 引用）
  'lollipop': LucideIcons.lollipop,
  'popcorn': LucideIcons.popcorn,
  'milk': LucideIcons.milk,
  'cupSoda': LucideIcons.cupSoda,
  'glassWater': LucideIcons.glassWater,
  'chefHat': LucideIcons.chefHat,
  'soup': LucideIcons.soup,
  'carrot': LucideIcons.carrot,
  'beef': LucideIcons.beef,
  'fish': LucideIcons.fish,
  'apple': LucideIcons.apple,
  'banana': LucideIcons.banana,
  'citrus': LucideIcons.citrus,
  'grape': LucideIcons.grape,
  'cherry': LucideIcons.cherry,

  // 交通出行
  'car': LucideIcons.car,
  'bus': LucideIcons.bus,
  'train': LucideIcons.train,
  'plane': LucideIcons.plane,
  'bike': LucideIcons.bike,
  'footprints': LucideIcons.footprints,
  'fuel': LucideIcons.fuel,
  'parkingCircle': LucideIcons.parkingCircle,
  'truck': LucideIcons.truck,
  'navigation': LucideIcons.navigation,

  // 购物消费
  'shoppingCart': LucideIcons.shoppingCart,
  'shoppingBag': LucideIcons.shoppingBag,
  'store': LucideIcons.store,
  'gift': LucideIcons.gift,
  'ticket': LucideIcons.ticket,
  'gem': LucideIcons.gem,
  'watch': LucideIcons.watch,
  'shirt': LucideIcons.shirt,
  'package': LucideIcons.package,
  'boxes': LucideIcons.boxes,
  'tags': LucideIcons.tags,
  'badgePercent': LucideIcons.badgePercent,

  // 居住生活
  'home': LucideIcons.home,
  'building': LucideIcons.building,
  'building2': LucideIcons.building2,
  'sofa': LucideIcons.sofa,
  'bed': LucideIcons.bed,
  'bath': LucideIcons.bath,
  'armchair': LucideIcons.armchair,
  'tv': LucideIcons.tv,
  'refrigerator': LucideIcons.refrigerator,
  'lightbulb': LucideIcons.lightbulb,
  'airVent': LucideIcons.airVent,
  'key': LucideIcons.key,
  'wrench': LucideIcons.wrench,
  'hammer': LucideIcons.hammer,
  'paintbrush': LucideIcons.paintbrush,
  'sprayCan': LucideIcons.sprayCan,
  'brush': LucideIcons.brush,
  'scroll': LucideIcons.scroll,
  'zap': LucideIcons.zap,
  'droplet': LucideIcons.droplet,
  'droplets': LucideIcons.droplets,
  'wind': LucideIcons.wind,
  'plug': LucideIcons.plug,
  'landmark': LucideIcons.landmark,
  'shield': LucideIcons.shield,
  'shieldCheck': LucideIcons.shieldCheck,
  'alertTriangle': LucideIcons.alertTriangle,
  'waves': LucideIcons.waves,
  'showerHead': LucideIcons.showerHead,
  'umbrella': LucideIcons.umbrella,
  'sun': LucideIcons.sun,
  'moon': LucideIcons.moon,
  'sunrise': LucideIcons.sunrise,

  // 通讯设备
  'phone': LucideIcons.phone,
  'smartphone': LucideIcons.smartphone,
  'monitor': LucideIcons.monitor,
  'laptop': LucideIcons.laptop,
  'tablet': LucideIcons.tablet,
  'keyboard': LucideIcons.keyboard,
  'mouse': LucideIcons.mouse,
  'wifi': LucideIcons.wifi,
  'router': LucideIcons.router,
  'headphones': LucideIcons.headphones,
  'phoneIncoming': LucideIcons.phoneIncoming,
  'phoneOutgoing': LucideIcons.phoneOutgoing,

  // 娱乐休闲
  'clapperboard': LucideIcons.clapperboard,
  'music': LucideIcons.music,
  'gamepad2': LucideIcons.gamepad2,
  'goal': LucideIcons.goal,
  'medal': LucideIcons.medal,
  'trophy': LucideIcons.trophy,
  'target': LucideIcons.target,
  'venetianMask': LucideIcons.venetianMask,
  'camera': LucideIcons.camera,
  'video': LucideIcons.video,
  'film': LucideIcons.film,
  'palette': LucideIcons.palette,
  'mic': LucideIcons.mic,
  'ferrisWheel': LucideIcons.ferrisWheel,
  'partyPopper': LucideIcons.partyPopper,
  'mountain': LucideIcons.mountain,
  'dice5': LucideIcons.dice5,
  'crown': LucideIcons.crown,
  'award': LucideIcons.award,
  'playCircle': LucideIcons.playCircle,
  'cloud': LucideIcons.cloud,
  'repeat': LucideIcons.repeat,
  'calendarClock': LucideIcons.calendarClock,

  // 健康医疗
  'cross': LucideIcons.cross,
  'stethoscope': LucideIcons.stethoscope,
  'pill': LucideIcons.pill,
  'syringe': LucideIcons.syringe,
  'thermometer': LucideIcons.thermometer,
  'heartPulse': LucideIcons.heartPulse,
  'activity': LucideIcons.activity,
  'brain': LucideIcons.brain,
  'smile': LucideIcons.smile,
  'scissors': LucideIcons.scissors,
  'hand': LucideIcons.hand,
  'salad': LucideIcons.salad,
  'dumbbell': LucideIcons.dumbbell,
  'sparkles': LucideIcons.sparkles,
  'sparkle': LucideIcons.sparkle,
  'flower': LucideIcons.flower,
  'flower2': LucideIcons.flower2,
  'biohazard': LucideIcons.biohazard,
  'atom': LucideIcons.atom,
  'info': LucideIcons.info,
  'clipboardList': LucideIcons.clipboardList,
  'user': LucideIcons.user,

  // 教育学习
  'graduationCap': LucideIcons.graduationCap,
  'bookOpen': LucideIcons.bookOpen,
  'bookMarked': LucideIcons.bookMarked,
  'library': LucideIcons.library,
  'pencil': LucideIcons.pencil,
  'edit2': LucideIcons.edit2,
  'calculator': LucideIcons.calculator,
  'flaskConical': LucideIcons.flaskConical,
  'languages': LucideIcons.languages,
  'presentation': LucideIcons.presentation,
  'badgeHelp': LucideIcons.badgeHelp,

  // 宠物自然
  'dog': LucideIcons.dog,
  'cat': LucideIcons.cat,
  'bone': LucideIcons.bone,
  'bug': LucideIcons.bug,
  'treePine': LucideIcons.treePine,
  'trees': LucideIcons.trees,
  'shrub': LucideIcons.shrub,
  'leaf': LucideIcons.leaf,
  'sprout': LucideIcons.sprout,
  'wheat': LucideIcons.wheat,

  // 工作金融
  'briefcase': LucideIcons.briefcase,
  'code': LucideIcons.code,
  'penTool': LucideIcons.penTool,
  'hardHat': LucideIcons.hardHat,
  'factory': LucideIcons.factory,
  'piggyBank': LucideIcons.piggyBank,
  'trendingUp': LucideIcons.trendingUp,
  'trendingDown': LucideIcons.trendingDown,
  'lineChart': LucideIcons.lineChart,
  'barChart3': LucideIcons.barChart3,
  'percent': LucideIcons.percent,
  'circleDollarSign': LucideIcons.circleDollarSign,
  'badgeDollarSign': LucideIcons.badgeDollarSign,
  'arrowLeftRight': LucideIcons.arrowLeftRight,
  'creditCard': LucideIcons.creditCard,
  'wallet': LucideIcons.wallet,
  'walletCards': LucideIcons.walletCards,
  'banknote': LucideIcons.banknote,
  'coins': LucideIcons.coins,
  'handCoins': LucideIcons.handCoins,
  'receipt': LucideIcons.receipt,
  'fileText': LucideIcons.fileText,
  'euro': LucideIcons.euro,
  'japaneseYen': LucideIcons.japaneseYen,
  'scale': LucideIcons.scale,
  'badgeCheck': LucideIcons.badgeCheck,

  // 社交人情
  'users': LucideIcons.users,
  'users2': LucideIcons.users2,
  'userPlus': LucideIcons.userPlus,
  'heartHandshake': LucideIcons.heartHandshake,
  'baby': LucideIcons.baby,

  // 其他杂项
  'checkCircle2': LucideIcons.checkCircle2,
  'clock': LucideIcons.clock,
  'timer': LucideIcons.timer,
  'undo': LucideIcons.undo,
  'refreshCw': LucideIcons.refreshCw,
  'rotateCw': LucideIcons.rotateCw,
  'rotateCcw': LucideIcons.rotateCcw,
  'download': LucideIcons.download,
  'logIn': LucideIcons.logIn,
  'arrowDown': LucideIcons.arrowDown,
  'arrowDownToLine': LucideIcons.arrowDownToLine,
  'arrowUpDown': LucideIcons.arrowUpDown,
  'arrowRightLeft': LucideIcons.arrowRightLeft,
  'printer': LucideIcons.printer,
  'mail': LucideIcons.mail,
  'inbox': LucideIcons.inbox,
  'globe': LucideIcons.globe,
  'mapPin': LucideIcons.mapPin,
  'map': LucideIcons.map,
  'compass': LucideIcons.compass,
  'image': LucideIcons.image,
  'bell': LucideIcons.bell,
  'cigarette': LucideIcons.cigarette,
};
